apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  # namespace: default  # Change to your desired namespace if needed
spec:
  accessModes:
    - ReadWriteOnce  # Access mode for the volume
  resources:
    requests:
      storage: 1Gi  # Request 1 GiB of storage; adjust as needed
