apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  namespace: dev  # Change to your desired namespace if needed
spec:
  selector:
    app: mongo-db
  ports:
    - protocol: TCP
      port: 27017  # Port to access MongoDB
      targetPort: 27017  # Port in the container
  type: ClusterIP  # Use ClusterIP for internal access
